// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTrack.Backend.Infrastructure.Persistence;

#nullable disable

namespace TimeTrack.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TimeTrackDbContext))]
    [Migration("20260514150000_CatchupMissingMigrations")]
    partial class CatchupMissingMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a catch-up migration, model snapshot remains the same
            // The actual model changes are defined in the main migrations
#pragma warning restore 612, 618
        }
    }
}
