using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TimeTrack.Backend.Domain.Entities;

namespace TimeTrack.Backend.Infrastructure.Persistence.Configurations;

internal sealed class ActivitySessionConfiguration : IEntityTypeConfiguration<ActivitySession>
{
    public void Configure(EntityTypeBuilder<ActivitySession> builder)
    {
        builder.ToTable("activity_sessions");

        builder.HasKey(a => a.Id);

        builder.Property(a => a.Id)
            .HasColumnName("id")
            .ValueGeneratedNever(); // ID is generated by client (Agent), not by database

        builder.Property(a => a.OrgId)
            .HasColumnName("org_id")
            .IsRequired();

        builder.Property(a => a.DeviceId)
            .HasColumnName("device_id")
            .IsRequired();

        builder.Property(a => a.UserId)
            .HasColumnName("user_id")
            .IsRequired();

        builder.Property(a => a.ProcessName)
            .HasColumnName("process_name")
            .HasMaxLength(255)
            .IsRequired();

        builder.Property(a => a.WindowTitle)
            .HasColumnName("window_title")
            .HasMaxLength(500);

        builder.Property(a => a.FilePath)
            .HasColumnName("file_path")
            .HasMaxLength(1000);

        builder.Property(a => a.AppCategory)
            .HasColumnName("app_category")
            .HasMaxLength(100);

        builder.Property(a => a.AppSubcategory)
            .HasColumnName("app_subcategory")
            .HasMaxLength(100);

        builder.Property(a => a.StartedAt)
            .HasColumnName("started_at")
            .IsRequired();

        builder.Property(a => a.EndedAt)
            .HasColumnName("ended_at")
            .IsRequired();

        builder.Property(a => a.DurationSeconds)
            .HasColumnName("duration_seconds")
            .IsRequired();

        builder.Property(a => a.IdempotencyKey)
            .HasColumnName("idempotency_key")
            .HasMaxLength(64)
            .IsRequired();

        builder.HasIndex(a => a.IdempotencyKey)
            .IsUnique();

        builder.Property(a => a.CreatedAt)
            .HasColumnName("created_at")
            .HasDefaultValueSql("now()");

        builder.Property(a => a.ProjectId)
            .HasColumnName("project_id");

        builder.Property(a => a.TaskId)
            .HasColumnName("task_id");

        // Indexes for queries
        builder.HasIndex(a => new { a.OrgId, a.UserId, a.StartedAt });
        // Covering index for per-user date-range queries (activity page, reports).
        // The (OrgId, UserId, StartedAt) index above cannot be used when OrgId is not
        // in the WHERE clause — the DB falls back to a table scan. This index makes
        // GetByUserIdAndDateRangeAsync, GetTopAppsAsync and GetDailySummaryRangeAsync fast.
        builder.HasIndex(a => new { a.UserId, a.StartedAt })
               .HasDatabaseName("ix_activity_sessions_user_started")
               .IsDescending(false, true);
        builder.HasIndex(a => new { a.DeviceId, a.StartedAt });
        builder.HasIndex(a => a.ProjectId);
        builder.HasIndex(a => a.TaskId);

        builder.HasOne(a => a.Project)
            .WithMany()
            .HasForeignKey(a => a.ProjectId)
            .OnDelete(DeleteBehavior.SetNull);

        builder.HasOne(a => a.Task)
            .WithMany()
            .HasForeignKey(a => a.TaskId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
